"""
Report generation for dark web analysis.

Generates markdown reports with:
- Executive summary
- Key findings
- Artifacts extracted
- LLM-generated insights
- Recommendations
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Dict, Any, Optional

from crawl4ai_darkweb_osint.analysis.presets import get_preset_description
from crawl4ai_darkweb_osint.analysis.artifacts import (
    Artifact,
    summarize_artifacts,
    group_artifacts_by_type,
)

logger = logging.getLogger(__name__)


@dataclass
class AnalysisReport:
    """Generated analysis report."""

    title: str
    preset: str
    content_analyzed: str
    summary: str
    key_findings: List[str]
    artifacts: List[Artifact]
    insights: str
    recommendations: List[str]
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_markdown(self) -> str:
        """Convert report to markdown format."""
        sections = []

        # Title
        sections.append(f"# {self.title}\n")
        sections.append(f"**Analysis Type:** {self.preset}")
        sections.append(f"**Generated:** {self.timestamp}")
        sections.append(
            f"**Content Length:** {len(self.content_analyzed):,} characters\n"
        )

        # Executive Summary
        sections.append("## Executive Summary\n")
        sections.append(self.summary)
        sections.append("")

        # Key Findings
        if self.key_findings:
            sections.append("## Key Findings\n")
            for finding in self.key_findings:
                sections.append(f"- {finding}")
            sections.append("")

        # Extracted Artifacts
        if self.artifacts:
            sections.append("## Extracted Artifacts\n")

            groups = group_artifacts_by_type(self.artifacts)

            for artifact_type, type_artifacts in groups.items():
                sections.append(f"### {artifact_type.replace('_', ' ').title()}\n")
                sections.append(f"**Count:** {len(type_artifacts)}\n")

                for artifact in type_artifacts[:10]:  # Limit to 10 per type
                    sections.append(f"- `{artifact.value}`")
                    if artifact.context:
                        # Truncate context
                        context = (
                            artifact.context[:100] + "..."
                            if len(artifact.context) > 100
                            else artifact.context
                        )
                        sections.append(f"  - Context: {context}")

                if len(type_artifacts) > 10:
                    sections.append(f"\n*...and {len(type_artifacts) - 10} more*")

                sections.append("")

        # LLM Insights
        if self.insights:
            sections.append("## Analysis Insights\n")
            sections.append(self.insights)
            sections.append("")

        # Recommendations
        if self.recommendations:
            sections.append("## Recommendations\n")
            for rec in self.recommendations:
                sections.append(f"- {rec}")
            sections.append("")

        # Footer
        sections.append("---")
        sections.append("*Generated by Crawl4AI Dark Web OSINT Addon*")

        return "\n".join(sections)

    def to_dict(self) -> Dict[str, Any]:
        """Convert report to dictionary."""
        return {
            "title": self.title,
            "preset": self.preset,
            "timestamp": self.timestamp,
            "summary": self.summary,
            "key_findings": self.key_findings,
            "artifacts": summarize_artifacts(self.artifacts),
            "insights": self.insights,
            "recommendations": self.recommendations,
            "metadata": self.metadata,
        }


async def generate_report(
    content: str,
    preset: str,
    artifacts: Optional[List[Artifact]] = None,
    llm_insights: Optional[str] = None,
    title: Optional[str] = None,
) -> AnalysisReport:
    """
    Generate an analysis report.

    Args:
        content: Content that was analyzed
        preset: Analysis preset used
        artifacts: Extracted artifacts
        llm_insights: LLM-generated analysis
        title: Report title

    Returns:
        AnalysisReport instance
    """
    from crawl4ai_darkweb_osint.llm_providers import get_llm_client, get_config

    # Extract artifacts if not provided
    if artifacts is None:
        from crawl4ai_darkweb_osint.analysis.artifacts import extract_artifacts

        artifacts = extract_artifacts(content)

    # Generate summary using LLM
    summary = ""
    key_findings = []
    recommendations = []

    try:
        config = get_config()
        client = get_llm_client(config.llm)

        # Generate summary
        summary_prompt = f"""Summarize the following dark web content analysis in 2-3 paragraphs.

Preset: {preset}
Artifacts found: {len(artifacts)}

Content preview:
{content[:2000]}...

Provide a concise executive summary."""

        summary = await client.generate(summary_prompt)

        # Extract key findings
        findings_prompt = f"""Based on this analysis of dark web content, list 5-7 key findings.

Each finding should be a single sentence.

Content:
{content[:1500]}...

Return only the findings, one per line."""

        findings_response = await client.generate(findings_prompt)
        key_findings = [
            line.strip().lstrip("- ").lstrip("0123456789. ")
            for line in findings_response.strip().split("\n")
            if line.strip()
        ][:7]

        # Generate recommendations
        rec_prompt = f"""Based on this dark web threat analysis, provide 3-5 actionable recommendations.

Analysis preset: {preset}

Content:
{content[:1000]}...

Return only recommendations, one per line."""

        rec_response = await client.generate(rec_prompt)
        recommendations = [
            line.strip().lstrip("- ").lstrip("0123456789. ")
            for line in rec_response.strip().split("\n")
            if line.strip()
        ][:5]

        if hasattr(client, "close"):
            await client.close()

    except Exception as e:
        logger.warning(f"LLM report generation failed: {e}")
        summary = "Summary generation failed. See insights and artifacts below."

    # Create report
    report = AnalysisReport(
        title=title or f"Dark Web Analysis: {get_preset_description(preset)}",
        preset=preset,
        content_analyzed=content[:5000],  # Store preview
        summary=summary,
        key_findings=key_findings,
        artifacts=artifacts,
        insights=llm_insights or "",
        recommendations=recommendations,
    )

    return report


def save_report(report: AnalysisReport, filepath: str) -> None:
    """
    Save report to file.

    Args:
        report: Report to save
        filepath: Output file path
    """
    from pathlib import Path

    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)

    # Determine format from extension
    if filepath.endswith(".json"):
        import json

        with open(path, "w") as f:
            json.dump(report.to_dict(), f, indent=2)
    else:
        # Default to markdown
        with open(path, "w") as f:
            f.write(report.to_markdown())


# CLI entry point
if __name__ == "__main__":
    import argparse
    import asyncio

    parser = argparse.ArgumentParser(description="Report generation")
    parser.add_argument("content", help="Content file to analyze")
    parser.add_argument("--preset", default="threat_intel", help="Analysis preset")
    parser.add_argument("--output", "-o", help="Output file path")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown")

    args = parser.parse_args()

    async def main():
        with open(args.content) as f:
            content = f.read()

        report = await generate_report(
            content=content,
            preset=args.preset,
        )

        if args.output:
            save_report(report, args.output)
            print(f"Report saved to {args.output}")
        else:
            if args.format == "json":
                import json

                print(json.dumps(report.to_dict(), indent=2))
            else:
                print(report.to_markdown())

    asyncio.run(main())
